# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.cache/wt [current_project]
set_property parent.project_path /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /home/mikkeljaedicke/Zynq_Book/sem_project3/ip_cores [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_three_phase_pwm_0_0/three_phase_pwm_c_addsub_v12_0_i0/three_phase_pwm_c_addsub_v12_0_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_three_phase_pwm_0_0/three_phase_pwm_c_addsub_v12_0_i1/three_phase_pwm_c_addsub_v12_0_i1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_three_phase_pwm_0_0/three_phase_pwm_c_counter_binary_v12_0_i0/three_phase_pwm_c_counter_binary_v12_0_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_three_phase_pwm_0_0/three_phase_pwm_div_gen_v5_1_i0/three_phase_pwm_div_gen_v5_1_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_three_phase_pwm_0_0/three_phase_pwm_div_gen_v5_1_i1/three_phase_pwm_div_gen_v5_1_i1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_three_phase_pwm_0_0/three_phase_pwm_mult_gen_v12_0_i0/three_phase_pwm_mult_gen_v12_0_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_three_phase_pwm_0_0/three_phase_pwm_mult_gen_v12_0_i1/three_phase_pwm_mult_gen_v12_0_i1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_three_phase_pwm_0_0/constrs/three_phase_pwm.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_interfaces_0_0/interfaces_c_counter_binary_v12_0_i0/interfaces_c_counter_binary_v12_0_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_interfaces_0_0/constrs/interfaces.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
read_xdc /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/mikkeljaedicke/Zynq_Book/sem_project3/sem_project3.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
