webtalk_init -webtalk_dir /home/mikkeljaedicke/Zynq_Book/sem_project2/ip_cores/io/netlist/ip_catalog/interfaces.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 16 16:28:45 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210779069_174157381_210622961_845" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fc812aed09655de29c82fe6dc98307ac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bdaaa953-8c63-42f4-aed7-eddfda34eb28" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 15.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1729.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 15.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1330.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 1981547130 -regid "210779069_174157381_210622961_845" -xml /home/mikkeljaedicke/Zynq_Book/sem_project2/ip_cores/io/netlist/ip_catalog/interfaces.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/mikkeljaedicke/Zynq_Book/sem_project2/ip_cores/io/netlist/ip_catalog/interfaces.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/mikkeljaedicke/Zynq_Book/sem_project2/ip_cores/io/netlist/ip_catalog/interfaces.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
